### ISSUE TITLE
Clear chats button shows confirm label after clearing then starting new chat

### ISSUE THREAD

**Issue by adamlui** [adamlui/autoclear-chatgpt-history#3]
Your button shows confirm label if you clear chats, then start new chat @XiaoYingYo

**Comment by XiaoYingYo** [comment]
Sorry, after translation, I can't understand what you mean, can you re-express it in a different way of description

@adamlui

**Comment by adamlui** [comment]
@XiaoYingYo click Clear Conversations, then click Confirm Clear Conversations. The button appropriately disappears. Then, click New Chat and start typing. After conversations appears, the button re-appears, but with the wrong label of Confirm Clear Conversations

**Comment by XiaoYingYo** [comment]
> @XiaoYingYo click Clear Conversations, then click Confirm Clear Conversations. The button appropriately disappears. Then, click New Chat and start typing. After conversations appears in History, the button re-appears, but with the wrong label of Confirm Clear Conversations

I get it, I'll submit a new pull request

**Comment by XiaoYingYo** [comment]
I have submitted the pr
