### ISSUE TITLE
fetchMap.get(...).items is undefined

### ISSUE THREAD

**Issue by adamlui** [adamlui/autoclear-chatgpt-history#6]
@XiaoYingYo OpenAI updated their UI and your function no longer works

**Comment by XiaoYingYo** [comment]
ok i got it
I'll check it out and fix it in the near future

**Comment by adamlui** [comment]
@XiaoYingYo I removed the `fetchMap.get()` & hook function because `chatgpt.isLoaded()` always waits for the menu now, you can re-add the buttons if you decide to want them in the future using this promise instead
