### ISSUE TITLE
BUG: 无法使用本地化语言

### ISSUE THREAD

**Issue by ChinaGodMan** [adamlui/autoclear-chatgpt-history#65]
@adamlui 
获取`app.assetHostURL`失败 `msgHref`拼接失败
无法使用语言包了！
![Screenshot_20241015_044701_edit_247975030572779](https://github.com/user-attachments/assets/80418419-ea0a-4614-b8d3-c1f4a1ad452f)

**Comment by ChinaGodMan** [comment]
老铁
![Screenshot_20241015_045625_edit_248585785911893](https://github.com/user-attachments/assets/f8ab5415-08b5-4548-95c2-2eda2d2ac5ee)
，`assetHostURL`没在`app`对象里

**Comment by adamlui** [comment]
Thanks @ChinaGodMan !
